config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :tasks
  resources :users
  resources :categories, only: %i(index create destroy edit update)
  resources :labels,     only: %i(index create destroy edit update)
  root 'sessions#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/label.rb
class Label < ApplicationRecord
  has_many   :label_tables, dependent: :destroy
  has_many   :tasks, through: :label_tables
  belongs_to :user
end

app/models/label_table.rb
class LabelTable < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :logged_in_user

  def index
    @labels = current_user.labels
    @label  = Label.new
  end

  def create
    @label = current_user.labels.build(label_params)
    if @label.save
      flash[:success] = I18n.t 'label_create_success'
      redirect_to labels_url
    else
      flash.now[:danger] = I18n.t 'label_create_failed'
      @labels = Label.all
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    label = find_label_with_err_handling(params[:id])
    if label.destroy
      flash[:success] = I18n.t 'label_delete_success'
    else
      flash[:danger] = I18n.t 'label_delete_failed'
    end
    redirect_to labels_url
  end

  def edit
    @label = find_label_with_err_handling(params[:id])
  end

  def update
    @label = find_label_with_err_handling(params[:id])
    if @label.update(label_params)
      flash[:success] = I18n.t 'label_update_success'
      redirect_to labels_url
    else
      flash[:danger] = I18n.t 'label_update_failed'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def label_params
    params.require(:label).permit(:name)
  end

  def find_label_with_err_handling(label_id)
    label = Label.find_by(id: label_id)
    if label.nil?
      flash[:danger] = I18n.t 'label_not_exist'
      return redirect_to labels_url
    end

    label
  end
end

app/views/labels/edit.html.erb
<h1><%= "ラベル名の変更" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@label) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.submit '名前を変更', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class = "col-md-offset-3">
  <%=link_to  'キャンセル', labels_url %>
</div>

app/views/labels/index.html.erb
<h1><%= Label.model_name.human %></h1>

<div>
  <%= link_to I18n.t('tasks_index'), tasks_url %>
</div>

<%= form_for(@label) do |f| %>
  <%= f.label      :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.submit '作成', class: "btn btn-primary" %>
<% end %>

<ul class="labels">
  <% @labels.each do |l| %>
    <div>
      <span>
        <%= l.name %>
      </span>
      <span>
        <%= link_to '名前を変更', edit_label_path(l), class: "edit_label_#{l.id}"%>
      </span>
      <span>
        <%= button_to '削除', l, method: :delete,class: "delete_label_#{l.id}",
                      form: {data: {turbo_confirm: I18n.t('message_before_delete')} }%>
      </span>
    </div>
  <% end %>
</ul>