config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :tasks
  resources :users
  resources :categories, only: %i(index create destroy edit update)
  resources :labels,     only: %i(index create destroy edit update)
  root 'sessions#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/category.rb
class Category < ApplicationRecord
  DEFAULT_CREATED_CATEGORY = '未分類'.freeze

  belongs_to :user
  has_many :task, dependent: :restrict_with_error
  validates :name, presence: true, uniqueness: { scope: :user }

  def operation_prohibited?
    self.name == Category::DEFAULT_CREATED_CATEGORY
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = current_user.categories

    # current_user.categories.build と書くと
    # カテゴリ一覧にsave前のカテゴリが表示されてしまう
    @category   = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      flash[:success] = I18n.t 'category_create_success'
      redirect_to categories_url
    else
      flash.now[:danger] = I18n.t 'category_create_failed'
      @categories = Category.all
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    category = find_category_with_err_handling(params[:id])
    if category.destroy
      flash[:success] = I18n.t 'category_delete_success'
    else
      flash[:danger] = I18n.t 'category_delete_failed'
    end
    redirect_to categories_url
  end

  def edit
    @category = find_category_with_err_handling(params[:id])
  end

  def update
    @category = find_category_with_err_handling(params[:id])
    if @category.update(category_params)
      flash[:success] = I18n.t 'category_update_success'
      redirect_to categories_url
    else
      flash[:danger] = I18n.t 'category_update_failed'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def find_category_with_err_handling(category_id)
    category = Category.find_by(id: category_id)
    if category.nil?
      flash[:danger] = I18n.t 'category_not_exist'
      return redirect_to categories_url

    elsif category.operation_prohibited?
      flash[:danger] = I18n.t 'operation_not_allowed'
      return redirect_to categories_url
    end

    category
  end

  def confirm_current_user
    return unless @current_user.nil?

    # TODO: ログインユーザに置き換える
    @current_user = User.find_by(email: 'user_0@example.com') # seedで作成されるユーザ
  end

  def operation_allowed?(category)
    if category.name == Category::DEFAULT_CREATED_CATEGORY
      flash[:danger] = I18n.t 'operation_not_allowed'
      return false
    end

    true
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1><%= "カテゴリ名の変更" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@category) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.submit '名前を変更', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class = "col-md-offset-3">
  <%=link_to  'キャンセル', categories_url %>
</div>

app/views/categories/index.html.erb
<h1><%= Category.model_name.human %></h1>

<div>
  <%= link_to I18n.t('tasks_index'), tasks_url %>
</div>

<%= form_for(@category) do |f| %>
  <%= render 'shared/category_error_msg' %>
  <%= f.label      :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.submit '作成', class: "btn btn-primary" %>
<% end %>

<ul class="categories">
  <% @categories.each do |c| %>
    <div>
      <span>
        <%= c.name %>
      </span>
      <% unless c.operation_prohibited? %>
        <span>
        <%= link_to '名前を変更', edit_category_path(c), class: "edit_category_#{c.id}"%>
        </span>
        <span>
        <%= button_to '削除', c, method: :delete,class: "delete_category_#{c.id}",
                      form: {data: {turbo_confirm: I18n.t('message_before_delete')} }%>
        </span>
      <% end %>
    </div>
  <% end %>
</ul>